using System.Collections.Generic;

namespace SpreedlyCoreSharp.Domain
{
    public class Country
    {
        public string Alpha2 { get; set; }
        public string Alpha3 { get; set; }
        public string Numeric { get; set; }
        public string Name { get; set; }
    }

    public static class Countries
    {
        public static List<Country> List = new List<Country>
        {
            new Country { Alpha2 = "AF", Name = "Afghanistan", Alpha3 = "AFG", Numeric = "004" },
            new Country { Alpha2 = "AL", Name = "Albania", Alpha3 = "ALB", Numeric = "008" },
            new Country { Alpha2 = "DZ", Name = "Algeria", Alpha3 = "DZA", Numeric = "012" },
            new Country { Alpha2 = "AS", Name = "American Samoa", Alpha3 = "ASM", Numeric = "016" },
            new Country { Alpha2 = "AD", Name = "Andorra", Alpha3 = "AND", Numeric = "020" },
            new Country { Alpha2 = "AO", Name = "Angola", Alpha3 = "AGO", Numeric = "024" },
            new Country { Alpha2 = "AI", Name = "Anguilla", Alpha3 = "AIA", Numeric = "660" },
            new Country { Alpha2 = "AG", Name = "Antigua and Barbuda", Alpha3 = "ATG", Numeric = "028" },
            new Country { Alpha2 = "AR", Name = "Argentina", Alpha3 = "ARG", Numeric = "032" },
            new Country { Alpha2 = "AM", Name = "Armenia", Alpha3 = "ARM", Numeric = "051" },
            new Country { Alpha2 = "AW", Name = "Aruba", Alpha3 = "ABW", Numeric = "533" },
            new Country { Alpha2 = "AU", Name = "Australia", Alpha3 = "AUS", Numeric = "036" },
            new Country { Alpha2 = "AT", Name = "Austria", Alpha3 = "AUT", Numeric = "040" },
            new Country { Alpha2 = "AZ", Name = "Azerbaijan", Alpha3 = "AZE", Numeric = "031" },
            new Country { Alpha2 = "BS", Name = "Bahamas", Alpha3 = "BHS", Numeric = "044" },
            new Country { Alpha2 = "BH", Name = "Bahrain", Alpha3 = "BHR", Numeric = "048" },
            new Country { Alpha2 = "BD", Name = "Bangladesh", Alpha3 = "BGD", Numeric = "050" },
            new Country { Alpha2 = "BB", Name = "Barbados", Alpha3 = "BRB", Numeric = "052" },
            new Country { Alpha2 = "BY", Name = "Belarus", Alpha3 = "BLR", Numeric = "112" },
            new Country { Alpha2 = "BE", Name = "Belgium", Alpha3 = "BEL", Numeric = "056" },
            new Country { Alpha2 = "BZ", Name = "Belize", Alpha3 = "BLZ", Numeric = "084" },
            new Country { Alpha2 = "BJ", Name = "Benin", Alpha3 = "BEN", Numeric = "204" },
            new Country { Alpha2 = "BM", Name = "Bermuda", Alpha3 = "BMU", Numeric = "060" },
            new Country { Alpha2 = "BT", Name = "Bhutan", Alpha3 = "BTN", Numeric = "064" },
            new Country { Alpha2 = "BO", Name = "Bolivia", Alpha3 = "BOL", Numeric = "068" },
            new Country { Alpha2 = "BA", Name = "Bosnia and Herzegovina", Alpha3 = "BIH", Numeric = "070" },
            new Country { Alpha2 = "BW", Name = "Botswana", Alpha3 = "BWA", Numeric = "072" },
            new Country { Alpha2 = "BV", Name = "Bouvet Island", Alpha3 = "BVD", Numeric = "074" },
            new Country { Alpha2 = "BR", Name = "Brazil", Alpha3 = "BRA", Numeric = "076" },
            new Country { Alpha2 = "IO", Name = "British Indian Ocean Territory", Alpha3 = "IOT", Numeric = "086" },
            new Country { Alpha2 = "BN", Name = "Brunei Darussalam", Alpha3 = "BRN", Numeric = "096" },
            new Country { Alpha2 = "BG", Name = "Bulgaria", Alpha3 = "BGR", Numeric = "100" },
            new Country { Alpha2 = "BF", Name = "Burkina Faso", Alpha3 = "BFA", Numeric = "854" },
            new Country { Alpha2 = "BI", Name = "Burundi", Alpha3 = "BDI", Numeric = "108" },
            new Country { Alpha2 = "KH", Name = "Cambodia", Alpha3 = "KHM", Numeric = "116" },
            new Country { Alpha2 = "CM", Name = "Cameroon", Alpha3 = "CMR", Numeric = "120" },
            new Country { Alpha2 = "CA", Name = "Canada", Alpha3 = "CAN", Numeric = "124" },
            new Country { Alpha2 = "CV", Name = "Cape Verde", Alpha3 = "CPV", Numeric = "132" },
            new Country { Alpha2 = "KY", Name = "Cayman Islands", Alpha3 = "CYM", Numeric = "136" },
            new Country { Alpha2 = "CF", Name = "Central African Republic", Alpha3 = "CAF", Numeric = "140" },
            new Country { Alpha2 = "TD", Name = "Chad", Alpha3 = "TCD", Numeric = "148" },
            new Country { Alpha2 = "CL", Name = "Chile", Alpha3 = "CHL", Numeric = "152" },
            new Country { Alpha2 = "CN", Name = "China", Alpha3 = "CHN", Numeric = "156" },
            new Country { Alpha2 = "CX", Name = "Christmas Island", Alpha3 = "CXR", Numeric = "162" },
            new Country { Alpha2 = "CC", Name = "Cocos (Keeling) Islands", Alpha3 = "CCK", Numeric = "166" },
            new Country { Alpha2 = "CO", Name = "Colombia", Alpha3 = "COL", Numeric = "170" },
            new Country { Alpha2 = "KM", Name = "Comoros", Alpha3 = "COM", Numeric = "174" },
            new Country { Alpha2 = "CG", Name = "Congo", Alpha3 = "COG", Numeric = "178" },
            new Country { Alpha2 = "CD", Name = "Congo, the Democratic Republic of the", Alpha3 = "COD", Numeric = "180" },
            new Country { Alpha2 = "CK", Name = "Cook Islands", Alpha3 = "COK", Numeric = "184" },
            new Country { Alpha2 = "CR", Name = "Costa Rica", Alpha3 = "CRI", Numeric = "188" },
            new Country { Alpha2 = "CI", Name = "Cote D\"Ivoire", Alpha3 = "CIV", Numeric = "384" },
            new Country { Alpha2 = "HR", Name = "Croatia", Alpha3 = "HRV", Numeric = "191" },
            new Country { Alpha2 = "CU", Name = "Cuba", Alpha3 = "CUB", Numeric = "192" },
            new Country { Alpha2 = "CY", Name = "Cyprus", Alpha3 = "CYP", Numeric = "196" },
            new Country { Alpha2 = "CZ", Name = "Czech Republic", Alpha3 = "CZE", Numeric = "203" },
            new Country { Alpha2 = "DK", Name = "Denmark", Alpha3 = "DNK", Numeric = "208" },
            new Country { Alpha2 = "DJ", Name = "Djibouti", Alpha3 = "DJI", Numeric = "262" },
            new Country { Alpha2 = "DM", Name = "Dominica", Alpha3 = "DMA", Numeric = "212" },
            new Country { Alpha2 = "DO", Name = "Dominican Republic", Alpha3 = "DOM", Numeric = "214" },
            new Country { Alpha2 = "EC", Name = "Ecuador", Alpha3 = "ECU", Numeric = "218" },
            new Country { Alpha2 = "EG", Name = "Egypt", Alpha3 = "EGY", Numeric = "818" },
            new Country { Alpha2 = "SV", Name = "El Salvador", Alpha3 = "SLV", Numeric = "222" },
            new Country { Alpha2 = "GQ", Name = "Equatorial Guinea", Alpha3 = "GNQ", Numeric = "226" },
            new Country { Alpha2 = "ER", Name = "Eritrea", Alpha3 = "ERI", Numeric = "232" },
            new Country { Alpha2 = "EE", Name = "Estonia", Alpha3 = "EST", Numeric = "233" },
            new Country { Alpha2 = "ET", Name = "Ethiopia", Alpha3 = "ETH", Numeric = "231" },
            new Country { Alpha2 = "FK", Name = "Falkland Islands (Malvinas)", Alpha3 = "FLK", Numeric = "238" },
            new Country { Alpha2 = "FO", Name = "Faroe Islands", Alpha3 = "FRO", Numeric = "234" },
            new Country { Alpha2 = "FJ", Name = "Fiji", Alpha3 = "FJI", Numeric = "242" },
            new Country { Alpha2 = "FI", Name = "Finland", Alpha3 = "FIN", Numeric = "246" },
            new Country { Alpha2 = "FR", Name = "France", Alpha3 = "FRA", Numeric = "250" },
            new Country { Alpha2 = "GF", Name = "French Guiana", Alpha3 = "GUF", Numeric = "254" },
            new Country { Alpha2 = "PF", Name = "French Polynesia", Alpha3 = "PYF", Numeric = "258" },
            new Country { Alpha2 = "TF", Name = "French Southern Territories", Alpha3 = "ATF", Numeric = "260" },
            new Country { Alpha2 = "GA", Name = "Gabon", Alpha3 = "GAB", Numeric = "266" },
            new Country { Alpha2 = "GM", Name = "Gambia", Alpha3 = "GMB", Numeric = "270" },
            new Country { Alpha2 = "GE", Name = "Georgia", Alpha3 = "GEO", Numeric = "268" },
            new Country { Alpha2 = "DE", Name = "Germany", Alpha3 = "DEU", Numeric = "276" },
            new Country { Alpha2 = "GH", Name = "Ghana", Alpha3 = "GHA", Numeric = "288" },
            new Country { Alpha2 = "GI", Name = "Gibraltar", Alpha3 = "GIB", Numeric = "292" },
            new Country { Alpha2 = "GR", Name = "Greece", Alpha3 = "GRC", Numeric = "300" },
            new Country { Alpha2 = "GL", Name = "Greenland", Alpha3 = "GRL", Numeric = "304" },
            new Country { Alpha2 = "GD", Name = "Grenada", Alpha3 = "GRD", Numeric = "308" },
            new Country { Alpha2 = "GP", Name = "Guadeloupe", Alpha3 = "GLP", Numeric = "312" },
            new Country { Alpha2 = "GU", Name = "Guam", Alpha3 = "GUM", Numeric = "316" },
            new Country { Alpha2 = "GT", Name = "Guatemala", Alpha3 = "GTM", Numeric = "320" },
            new Country { Alpha2 = "GG", Name = "Guernsey", Alpha3 = "GGY", Numeric = "831" },
            new Country { Alpha2 = "GN", Name = "Guinea", Alpha3 = "GIN", Numeric = "324" },
            new Country { Alpha2 = "GW", Name = "Guinea-Bissau", Alpha3 = "GNB", Numeric = "624" },
            new Country { Alpha2 = "GY", Name = "Guyana", Alpha3 = "GUY", Numeric = "328" },
            new Country { Alpha2 = "HT", Name = "Haiti", Alpha3 = "HTI", Numeric = "332" },
            new Country { Alpha2 = "HM", Name = "Heard Island And Mcdonald Islands", Alpha3 = "HMD", Numeric = "334" },
            new Country { Alpha2 = "VA", Name = "Holy See (Vatican City State)", Alpha3 = "VAT", Numeric = "336" },
            new Country { Alpha2 = "HN", Name = "Honduras", Alpha3 = "HND", Numeric = "340" },
            new Country { Alpha2 = "HK", Name = "Hong Kong", Alpha3 = "HKG", Numeric = "344" },
            new Country { Alpha2 = "HU", Name = "Hungary", Alpha3 = "HUN", Numeric = "348" },
            new Country { Alpha2 = "IS", Name = "Iceland", Alpha3 = "ISL", Numeric = "352" },
            new Country { Alpha2 = "IN", Name = "India", Alpha3 = "IND", Numeric = "356" },
            new Country { Alpha2 = "ID", Name = "Indonesia", Alpha3 = "IDN", Numeric = "360" },
            new Country { Alpha2 = "IR", Name = "Iran, Islamic Republic of", Alpha3 = "IRN", Numeric = "364" },
            new Country { Alpha2 = "IQ", Name = "Iraq", Alpha3 = "IRQ", Numeric = "368" },
            new Country { Alpha2 = "IE", Name = "Ireland", Alpha3 = "IRL", Numeric = "372" },
            new Country { Alpha2 = "IM", Name = "Isle Of Man", Alpha3 = "IMN", Numeric = "833" },
            new Country { Alpha2 = "IL", Name = "Israel", Alpha3 = "ISR", Numeric = "376" },
            new Country { Alpha2 = "IT", Name = "Italy", Alpha3 = "ITA", Numeric = "380" },
            new Country { Alpha2 = "JM", Name = "Jamaica", Alpha3 = "JAM", Numeric = "388" },
            new Country { Alpha2 = "JP", Name = "Japan", Alpha3 = "JPN", Numeric = "392" },
            new Country { Alpha2 = "JE", Name = "Jersey", Alpha3 = "JEY", Numeric = "832" },
            new Country { Alpha2 = "JO", Name = "Jordan", Alpha3 = "JOR", Numeric = "400" },
            new Country { Alpha2 = "KZ", Name = "Kazakhstan", Alpha3 = "KAZ", Numeric = "398" },
            new Country { Alpha2 = "KE", Name = "Kenya", Alpha3 = "KEN", Numeric = "404" },
            new Country { Alpha2 = "KI", Name = "Kiribati", Alpha3 = "KIR", Numeric = "296" },
            new Country { Alpha2 = "KP", Name = "Korea, Democratic People\"s Republic of", Alpha3 = "PRK", Numeric = "408" },
            new Country { Alpha2 = "KR", Name = "Korea, Republic of", Alpha3 = "KOR", Numeric = "410" },
            new Country { Alpha2 = "KW", Name = "Kuwait", Alpha3 = "KWT", Numeric = "414" },
            new Country { Alpha2 = "KG", Name = "Kyrgyzstan", Alpha3 = "KGZ", Numeric = "417" },
            new Country { Alpha2 = "LA", Name = "Lao People\"s Democratic Republic", Alpha3 = "LAO", Numeric = "418" },
            new Country { Alpha2 = "LV", Name = "Latvia", Alpha3 = "LVA", Numeric = "428" },
            new Country { Alpha2 = "LB", Name = "Lebanon", Alpha3 = "LBN", Numeric = "422" },
            new Country { Alpha2 = "LS", Name = "Lesotho", Alpha3 = "LSO", Numeric = "426" },
            new Country { Alpha2 = "LR", Name = "Liberia", Alpha3 = "LBR", Numeric = "430" },
            new Country { Alpha2 = "LY", Name = "Libyan Arab Jamahiriya", Alpha3 = "LBY", Numeric = "434" },
            new Country { Alpha2 = "LI", Name = "Liechtenstein", Alpha3 = "LIE", Numeric = "438" },
            new Country { Alpha2 = "LT", Name = "Lithuania", Alpha3 = "LTU", Numeric = "440" },
            new Country { Alpha2 = "LU", Name = "Luxembourg", Alpha3 = "LUX", Numeric = "442" },
            new Country { Alpha2 = "MO", Name = "Macao", Alpha3 = "MAC", Numeric = "446" },
            new Country { Alpha2 = "MK", Name = "Macedonia, the Former Yugoslav Republic of", Alpha3 = "MKD", Numeric = "807" },
            new Country { Alpha2 = "MG", Name = "Madagascar", Alpha3 = "MDG", Numeric = "450" },
            new Country { Alpha2 = "MW", Name = "Malawi", Alpha3 = "MWI", Numeric = "454" },
            new Country { Alpha2 = "MY", Name = "Malaysia", Alpha3 = "MYS", Numeric = "458" },
            new Country { Alpha2 = "MV", Name = "Maldives", Alpha3 = "MDV", Numeric = "462" },
            new Country { Alpha2 = "ML", Name = "Mali", Alpha3 = "MLI", Numeric = "466" },
            new Country { Alpha2 = "MT", Name = "Malta", Alpha3 = "MLT", Numeric = "470" },
            new Country { Alpha2 = "MH", Name = "Marshall Islands", Alpha3 = "MHL", Numeric = "584" },
            new Country { Alpha2 = "MQ", Name = "Martinique", Alpha3 = "MTQ", Numeric = "474" },
            new Country { Alpha2 = "MR", Name = "Mauritania", Alpha3 = "MRT", Numeric = "478" },
            new Country { Alpha2 = "MU", Name = "Mauritius", Alpha3 = "MUS", Numeric = "480" },
            new Country { Alpha2 = "YT", Name = "Mayotte", Alpha3 = "MYT", Numeric = "175" },
            new Country { Alpha2 = "MX", Name = "Mexico", Alpha3 = "MEX", Numeric = "484" },
            new Country { Alpha2 = "FM", Name = "Micronesia, Federated States of", Alpha3 = "FSM", Numeric = "583" },
            new Country { Alpha2 = "MD", Name = "Moldova, Republic of", Alpha3 = "MDA", Numeric = "498" },
            new Country { Alpha2 = "MC", Name = "Monaco", Alpha3 = "MCO", Numeric = "492" },
            new Country { Alpha2 = "MN", Name = "Mongolia", Alpha3 = "MNG", Numeric = "496" },
            new Country { Alpha2 = "ME", Name = "Montenegro", Alpha3 = "MNE", Numeric = "499" },
            new Country { Alpha2 = "MS", Name = "Montserrat", Alpha3 = "MSR", Numeric = "500" },
            new Country { Alpha2 = "MA", Name = "Morocco", Alpha3 = "MAR", Numeric = "504" },
            new Country { Alpha2 = "MZ", Name = "Mozambique", Alpha3 = "MOZ", Numeric = "508" },
            new Country { Alpha2 = "MM", Name = "Myanmar", Alpha3 = "MMR", Numeric = "104" },
            new Country { Alpha2 = "NA", Name = "Namibia", Alpha3 = "NAM", Numeric = "516" },
            new Country { Alpha2 = "NR", Name = "Nauru", Alpha3 = "NRU", Numeric = "520" },
            new Country { Alpha2 = "NP", Name = "Nepal", Alpha3 = "NPL", Numeric = "524" },
            new Country { Alpha2 = "NL", Name = "Netherlands", Alpha3 = "NLD", Numeric = "528" },
            new Country { Alpha2 = "AN", Name = "Netherlands Antilles", Alpha3 = "ANT", Numeric = "530" },
            new Country { Alpha2 = "NC", Name = "New Caledonia", Alpha3 = "NCL", Numeric = "540" },
            new Country { Alpha2 = "NZ", Name = "New Zealand", Alpha3 = "NZL", Numeric = "554" },
            new Country { Alpha2 = "NI", Name = "Nicaragua", Alpha3 = "NIC", Numeric = "558" },
            new Country { Alpha2 = "NE", Name = "Niger", Alpha3 = "NER", Numeric = "562" },
            new Country { Alpha2 = "NG", Name = "Nigeria", Alpha3 = "NGA", Numeric = "566" },
            new Country { Alpha2 = "NU", Name = "Niue", Alpha3 = "NIU", Numeric = "570" },
            new Country { Alpha2 = "NF", Name = "Norfolk Island", Alpha3 = "NFK", Numeric = "574" },
            new Country { Alpha2 = "MP", Name = "Northern Mariana Islands", Alpha3 = "MNP", Numeric = "580" },
            new Country { Alpha2 = "NO", Name = "Norway", Alpha3 = "NOR", Numeric = "578" },
            new Country { Alpha2 = "OM", Name = "Oman", Alpha3 = "OMN", Numeric = "512" },
            new Country { Alpha2 = "PK", Name = "Pakistan", Alpha3 = "PAK", Numeric = "586" },
            new Country { Alpha2 = "PW", Name = "Palau", Alpha3 = "PLW", Numeric = "585" },
            new Country { Alpha2 = "PS", Name = "Palestinian Territory, Occupied", Alpha3 = "PSE", Numeric = "275" },
            new Country { Alpha2 = "PA", Name = "Panama", Alpha3 = "PAN", Numeric = "591" },
            new Country { Alpha2 = "PG", Name = "Papua New Guinea", Alpha3 = "PNG", Numeric = "598" },
            new Country { Alpha2 = "PY", Name = "Paraguay", Alpha3 = "PRY", Numeric = "600" },
            new Country { Alpha2 = "PE", Name = "Peru", Alpha3 = "PER", Numeric = "604" },
            new Country { Alpha2 = "PH", Name = "Philippines", Alpha3 = "PHL", Numeric = "608" },
            new Country { Alpha2 = "PN", Name = "Pitcairn", Alpha3 = "PCN", Numeric = "612" },
            new Country { Alpha2 = "PL", Name = "Poland", Alpha3 = "POL", Numeric = "616" },
            new Country { Alpha2 = "PT", Name = "Portugal", Alpha3 = "PRT", Numeric = "620" },
            new Country { Alpha2 = "PR", Name = "Puerto Rico", Alpha3 = "PRI", Numeric = "630" },
            new Country { Alpha2 = "QA", Name = "Qatar", Alpha3 = "QAT", Numeric = "634" },
            new Country { Alpha2 = "RE", Name = "Reunion", Alpha3 = "REU", Numeric = "638" },
            new Country { Alpha2 = "RO", Name = "Romania", Alpha3 = "ROM", Numeric = "642" },
            new Country { Alpha2 = "RU", Name = "Russian Federation", Alpha3 = "RUS", Numeric = "643" },
            new Country { Alpha2 = "RW", Name = "Rwanda", Alpha3 = "RWA", Numeric = "646" },
            new Country { Alpha2 = "BL", Name = "Saint Barthélemy", Alpha3 = "BLM", Numeric = "652" },
            new Country { Alpha2 = "SH", Name = "Saint Helena", Alpha3 = "SHN", Numeric = "654" },
            new Country { Alpha2 = "KN", Name = "Saint Kitts and Nevis", Alpha3 = "KNA", Numeric = "659" },
            new Country { Alpha2 = "LC", Name = "Saint Lucia", Alpha3 = "LCA", Numeric = "662" },
            new Country { Alpha2 = "MF", Name = "Saint Martin (French part)", Alpha3 = "MAF", Numeric = "663" },
            new Country { Alpha2 = "PM", Name = "Saint Pierre and Miquelon", Alpha3 = "SPM", Numeric = "666" },
            new Country { Alpha2 = "VC", Name = "Saint Vincent and the Grenadines", Alpha3 = "VCT", Numeric = "670" },
            new Country { Alpha2 = "WS", Name = "Samoa", Alpha3 = "WSM", Numeric = "882" },
            new Country { Alpha2 = "SM", Name = "San Marino", Alpha3 = "SMR", Numeric = "674" },
            new Country { Alpha2 = "ST", Name = "Sao Tome and Principe", Alpha3 = "STP", Numeric = "678" },
            new Country { Alpha2 = "SA", Name = "Saudi Arabia", Alpha3 = "SAU", Numeric = "682" },
            new Country { Alpha2 = "SN", Name = "Senegal", Alpha3 = "SEN", Numeric = "686" },
            new Country { Alpha2 = "RS", Name = "Serbia", Alpha3 = "SRB", Numeric = "688" },
            new Country { Alpha2 = "SC", Name = "Seychelles", Alpha3 = "SYC", Numeric = "690" },
            new Country { Alpha2 = "SL", Name = "Sierra Leone", Alpha3 = "SLE", Numeric = "694" },
            new Country { Alpha2 = "SG", Name = "Singapore", Alpha3 = "SGP", Numeric = "702" },
            new Country { Alpha2 = "SK", Name = "Slovakia", Alpha3 = "SVK", Numeric = "703" },
            new Country { Alpha2 = "SI", Name = "Slovenia", Alpha3 = "SVN", Numeric = "705" },
            new Country { Alpha2 = "SB", Name = "Solomon Islands", Alpha3 = "SLB", Numeric = "090" },
            new Country { Alpha2 = "SO", Name = "Somalia", Alpha3 = "SOM", Numeric = "706" },
            new Country { Alpha2 = "ZA", Name = "South Africa", Alpha3 = "ZAF", Numeric = "710" },
            new Country { Alpha2 = "GS", Name = "South Georgia and the South Sandwich Islands", Alpha3 = "SGS", Numeric = "239" },
            new Country { Alpha2 = "ES", Name = "Spain", Alpha3 = "ESP", Numeric = "724" },
            new Country { Alpha2 = "LK", Name = "Sri Lanka", Alpha3 = "LKA", Numeric = "144" },
            new Country { Alpha2 = "SD", Name = "Sudan", Alpha3 = "SDN", Numeric = "736" },
            new Country { Alpha2 = "SR", Name = "SuriName", Alpha3 = "SUR", Numeric = "740" },
            new Country { Alpha2 = "SJ", Name = "Svalbard and Jan Mayen", Alpha3 = "SJM", Numeric = "744" },
            new Country { Alpha2 = "SZ", Name = "Swaziland", Alpha3 = "SWZ", Numeric = "748" },
            new Country { Alpha2 = "SE", Name = "Sweden", Alpha3 = "SWE", Numeric = "752" },
            new Country { Alpha2 = "CH", Name = "Switzerland", Alpha3 = "CHE", Numeric = "756" },
            new Country { Alpha2 = "SY", Name = "Syrian Arab Republic", Alpha3 = "SYR", Numeric = "760" },
            new Country { Alpha2 = "TW", Name = "Taiwan, Province of China", Alpha3 = "TWN", Numeric = "158" },
            new Country { Alpha2 = "TJ", Name = "Tajikistan", Alpha3 = "TJK", Numeric = "762" },
            new Country { Alpha2 = "TZ", Name = "Tanzania, United Republic of", Alpha3 = "TZA", Numeric = "834" },
            new Country { Alpha2 = "TH", Name = "Thailand", Alpha3 = "THA", Numeric = "764" },
            new Country { Alpha2 = "TL", Name = "Timor Leste", Alpha3 = "TLS", Numeric = "626" },
            new Country { Alpha2 = "TG", Name = "Togo", Alpha3 = "TGO", Numeric = "768" },
            new Country { Alpha2 = "TK", Name = "Tokelau", Alpha3 = "TKL", Numeric = "772" },
            new Country { Alpha2 = "TO", Name = "Tonga", Alpha3 = "TON", Numeric = "776" },
            new Country { Alpha2 = "TT", Name = "Trinidad and Tobago", Alpha3 = "TTO", Numeric = "780" },
            new Country { Alpha2 = "TN", Name = "Tunisia", Alpha3 = "TUN", Numeric = "788" },
            new Country { Alpha2 = "TR", Name = "Turkey", Alpha3 = "TUR", Numeric = "792" },
            new Country { Alpha2 = "TM", Name = "Turkmenistan", Alpha3 = "TKM", Numeric = "795" },
            new Country { Alpha2 = "TC", Name = "Turks and Caicos Islands", Alpha3 = "TCA", Numeric = "796" },
            new Country { Alpha2 = "TV", Name = "Tuvalu", Alpha3 = "TUV", Numeric = "798" },
            new Country { Alpha2 = "UG", Name = "Uganda", Alpha3 = "UGA", Numeric = "800" },
            new Country { Alpha2 = "UA", Name = "Ukraine", Alpha3 = "UKR", Numeric = "804" },
            new Country { Alpha2 = "AE", Name = "United Arab Emirates", Alpha3 = "ARE", Numeric = "784" },
            new Country { Alpha2 = "GB", Name = "United Kingdom", Alpha3 = "GBR", Numeric = "826" },
            new Country { Alpha2 = "US", Name = "United States", Alpha3 = "USA", Numeric = "840" },
            new Country { Alpha2 = "UM", Name = "United States Minor Outlying Islands", Alpha3 = "UMI", Numeric = "581" },
            new Country { Alpha2 = "UY", Name = "Uruguay", Alpha3 = "URY", Numeric = "858" },
            new Country { Alpha2 = "UZ", Name = "Uzbekistan", Alpha3 = "UZB", Numeric = "860" },
            new Country { Alpha2 = "VU", Name = "Vanuatu", Alpha3 = "VUT", Numeric = "548" },
            new Country { Alpha2 = "VE", Name = "Venezuela", Alpha3 = "VEN", Numeric = "862" },
            new Country { Alpha2 = "VN", Name = "Viet Nam", Alpha3 = "VNM", Numeric = "704" },
            new Country { Alpha2 = "VG", Name = "Virgin Islands, British", Alpha3 = "VGB", Numeric = "092" },
            new Country { Alpha2 = "VI", Name = "Virgin Islands, U.S.", Alpha3 = "VIR", Numeric = "850" },
            new Country { Alpha2 = "WF", Name = "Wallis and Futuna", Alpha3 = "WLF", Numeric = "876" },
            new Country { Alpha2 = "EH", Name = "Western Sahara", Alpha3 = "ESH", Numeric = "732" },
            new Country { Alpha2 = "YE", Name = "Yemen", Alpha3 = "YEM", Numeric = "887" },
            new Country { Alpha2 = "ZM", Name = "Zambia", Alpha3 = "ZMB", Numeric = "894" },
            new Country { Alpha2 = "ZW", Name = "Zimbabwe", Alpha3 = "ZWE", Numeric = "716" },
            new Country { Alpha2 = "AX", Name = "Åland Islands", Alpha3 = "ALA", Numeric = "248" }
        };
    }
}
